### PR TITLE
Added new optimization level

### PR DESCRIPTION
**Pull request by andreeapetian**
Added changes for optimization level on develop branch

### CODE REVIEW

**Comment by TommyMurphyTM1234** [comment]
Just wondering...
>```
> option.optimization.level.aggressive
> name="%option.optimization.level.aggressive"
>```
Should these names maybe make explicit that it's size that is being aggressively optimized here? E.g.:
>```
> option.optimization.level.size-aggressive
> name="%option.optimization.level.size-aggressive"
>```
Maybe some day GCC will add a similar aggressive option for execution time optimization?

**Comment by ilg-ul** [comment]
Oops! Tommy is right, the risc-v name must follow the same rule as the arm one.

**Comment by ilg-ul** [comment]
I'm a bit confused, I saw `-Oz` in the GCC manual, but my latest `arm-none-eabi-gcc`, 13.2, does not accept it.

What version do you know to accept it?

**Comment by TommyMurphyTM1234** [comment]
FWIW RISC-V GCC 13.2.0 built from https://github.com/riscv-collab/riscv-gnu-toolchain supports it:
```
riscv32-unknown-elf-gcc -v -Oz test.c -o
test
Using built-in specs.
COLLECT_GCC=./riscv32-unknown-elf-gcc
COLLECT_LTO_WRAPPER=/home/user/Downloads/riscv-gnu-toolchain/installed-tools/libexec/gcc/riscv32-unknown-elf/13.2.0/lto-wrapper
Target: riscv32-unknown-elf
Configured with: /home/user/Downloads/riscv-gnu-toolchain/gcc/configure --target=riscv32-unknown-elf --prefix=/home/user/Downloads/riscv-gnu-toolchain/installed-tools --disable-shared --disable-threads --enable-languages=c,c++ --with-pkgversion=gc891d8dc23e --with-system-zlib --enable-tls --with-newlib --with-sysroot=/home/user/Downloads/riscv-gnu-toolchain/installed-tools/riscv32-unknown-elf --with-native-system-header-dir=/include --disable-libmudflap --disable-libssp --disable-libquadmath --disable-libgomp --disable-nls --disable-tm-clone-registry --src=.././gcc --disable-multilib --with-abi=ilp32 --with-arch=rv32im --with-tune=rocket --with-isa-spec=20191213 'CFLAGS_FOR_TARGET=-Os    -mcmodel=medlow' 'CXXFLAGS_FOR_TARGET=-Os    -mcmodel=medlow'
Thread model: single
Supported LTO compression algorithms: zlib
gcc version 13.2.0 (gc891d8dc23e)
COLLECT_GCC_OPTIONS='-v' '-Oz' '-o' 'test' '-mtune=rocket' '-march=rv32im' '-mabi=ilp32' '-misa-spec=20191213' '-march=rv32im'
 /home/user/Downloads/riscv-gnu-toolchain/installed-tools/libexec/gcc/riscv32-unknown-elf/13.2.0/cc1 -quiet -v -imultilib . test.c -quiet -dumpbase test.c -dumpbase-ext .c -mtune=rocket -march=rv32im -mabi=ilp32 -misa-spec=20191213 -march=rv32im -Oz -version -o /tmp/ccTipdmk.s
GNU C17 (gc891d8dc23e) version 13.2.0 (riscv32-unknown-elf)
        compiled by GNU C version 11.4.0, GMP version 6.2.1, MPFR version 4.1.0, MPC version 1.2.1, isl version none
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/home/user/Downloads/riscv-gnu-toolchain/installed-tools/riscv32-unknown-elf/usr/local/include"
ignoring duplicate directory "/home/user/Downloads/riscv-gnu-toolchain/installed-tools/riscv32-unknown-elf/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/include
 /home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/include-fixed
 /home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/../../../../riscv32-unknown-elf/include
End of search list.
Compiler executable checksum: ddb203fe112ab30f2ec66259607278a7
COLLECT_GCC_OPTIONS='-v' '-Oz' '-o' 'test' '-mtune=rocket' '-march=rv32im' '-mabi=ilp32' '-misa-spec=20191213' '-march=rv32im'
 /home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/../../../../riscv32-unknown-elf/bin/as -v --traditional-format -march=rv32im -march=rv32im -mabi=ilp32 -misa-spec=20191213 -o /tmp/cc0uzpvO.o /tmp/ccTipdmk.s
GNU assembler version 2.41 (riscv32-unknown-elf) using BFD version (GNU Binutils) 2.41
COMPILER_PATH=/home/user/Downloads/riscv-gnu-toolchain/installed-tools/libexec/gcc/riscv32-unknown-elf/13.2.0/:/home/user/Downloads/riscv-gnu-toolchain/installed-tools/libexec/gcc/riscv32-unknown-elf/13.2.0/:/home/user/Downloads/riscv-gnu-toolchain/installed-tools/libexec/gcc/riscv32-unknown-elf/:/home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/:/home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/:/home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/../../../../riscv32-unknown-elf/bin/
LIBRARY_PATH=/home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/:/home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/../../../../riscv32-unknown-elf/lib/:/home/user/Downloads/riscv-gnu-toolchain/installed-tools/riscv32-unknown-elf/lib/
COLLECT_GCC_OPTIONS='-v' '-Oz' '-o' 'test' '-mtune=rocket' '-march=rv32im' '-mabi=ilp32' '-misa-spec=20191213' '-march=rv32im' '-dumpdir' 'test.'
 /home/user/Downloads/riscv-gnu-toolchain/installed-tools/libexec/gcc/riscv32-unknown-elf/13.2.0/collect2 -plugin /home/user/Downloads/riscv-gnu-toolchain/installed-tools/libexec/gcc/riscv32-unknown-elf/13.2.0/liblto_plugin.so -plugin-opt=/home/user/Downloads/riscv-gnu-toolchain/installed-tools/libexec/gcc/riscv32-unknown-elf/13.2.0/lto-wrapper -plugin-opt=-fresolution=/tmp/ccVCQbnO.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgloss -plugin-opt=-pass-through=-lgcc --sysroot=/home/user/Downloads/riscv-gnu-toolchain/installed-tools/riscv32-unknown-elf -melf32lriscv -o test /home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/../../../../riscv32-unknown-elf/lib/crt0.o /home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/crtbegin.o -L/home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0 -L/home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/../../../../riscv32-unknown-elf/lib -L/home/user/Downloads/riscv-gnu-toolchain/installed-tools/riscv32-unknown-elf/lib /tmp/cc0uzpvO.o -lgcc --start-group -lc -lgloss --end-group -lgcc /home/user/Downloads/riscv-gnu-toolchain/installed-tools/lib/gcc/riscv32-unknown-elf/13.2.0/crtend.o
COLLECT_GCC_OPTIONS='-v' '-Oz' '-o' 'test' '-mtune=rocket' '-march=rv32im' '-mabi=ilp32' '-misa-spec=20191213' '-march=rv32im' '-dumpdir' 'test.'
```

**Comment by ilg-ul** [comment]
Ok, thank you for checking.

**Comment by TommyMurphyTM1234** [comment]
Also this arm toolchain:

* https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads
  * https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads#:~:text=Windows%20(mingw%2Dw64,arm%2Dnone%2Deabi)

```
arm-none-eabi-gcc.exe -v -Oz test.c -o test.exe -nostartfiles
Using built-in specs.
COLLECT_GCC=arm-none-eabi-gcc.exe
COLLECT_LTO_WRAPPER=C:/Users/Tommy\ Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../libexec/gcc/arm-none-eabi/13.2.1/lto-wrapper.exe
Target: arm-none-eabi
Configured with: /data/jenkins/workspace/GNU-toolchain/arm-13/src/gcc/configure --target=arm-none-eabi --prefix=/data/jenkins/workspace/GNU-toolchain/arm-13/build-mingw-arm-none-eabi/install --with-gmp=/data/jenkins/workspace/GNU-toolchain/arm-13/build-mingw-arm-none-eabi/host-tools --with-mpfr=/data/jenkins/workspace/GNU-toolchain/arm-13/build-mingw-arm-none-eabi/host-tools --with-mpc=/data/jenkins/workspace/GNU-toolchain/arm-13/build-mingw-arm-none-eabi/host-tools --with-isl=/data/jenkins/workspace/GNU-toolchain/arm-13/build-mingw-arm-none-eabi/host-tools --disable-shared --disable-nls --disable-threads --disable-tls --enable-checking=release --enable-languages=c,c++,fortran --with-newlib --with-gnu-as --with-headers=yes --with-gnu-ld --with-native-system-header-dir=/include --with-sysroot=/data/jenkins/workspace/GNU-toolchain/arm-13/build-mingw-arm-none-eabi/install/arm-none-eabi --with-multilib-list=aprofile,rmprofile --with-libiconv-prefix=/data/jenkins/workspace/GNU-toolchain/arm-13/build-mingw-arm-none-eabi/host-tools --host=i686-w64-mingw32 --with-pkgversion='Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)' --with-bugurl=https://bugs.linaro.org/
Thread model: single
Supported LTO compression algorithms: zlib
gcc version 13.2.1 20231009 (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7))
COLLECT_GCC_OPTIONS='-v' '-Oz' '-o' 'test.exe' '-nostartfiles' '-mcpu=arm7tdmi' '-mfloat-abi=soft' '-marm' '-mlibarch=armv4t' '-march=armv4t'
 C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../libexec/gcc/arm-none-eabi/13.2.1/cc1.exe -quiet -v -iprefix C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/ -isysroot C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../arm-none-eabi -D__USES_INITFINI__ test.c -quiet -dumpbase test.c -dumpbase-ext .c -mcpu=arm7tdmi -mfloat-abi=soft -marm -mlibarch=armv4t -march=armv4t -Oz -version -o C:\Users\TOMMYM~1\AppData\Local\Temp\ccAqNSAw.s
GNU C17 (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) version 13.2.1 20231009 (arm-none-eabi)
        compiled by GNU C version 9.3-win32 20200320, GMP version 6.2.1, MPFR version 3.1.6, MPC version 1.0.3, isl version isl-0.15-1-g835ea3a-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring duplicate directory "C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/../../lib/gcc/arm-none-eabi/13.2.1/include"
ignoring nonexistent directory "C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../arm-none-eabi/data/jenkins/workspace/GNU-toolchain/arm-13/build-mingw-arm-none-eabi/install/lib/gcc/arm-none-eabi/13.2.1/../../../../include"
ignoring duplicate directory "C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/../../lib/gcc/arm-none-eabi/13.2.1/include-fixed"
ignoring duplicate directory "C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/lib/gcc/../../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/include"
ignoring duplicate directory "C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../arm-none-eabi/include"
#include "..." search starts here:
#include <...> search starts here:
 C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/include
 C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/include-fixed
 C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/include
End of search list.
Compiler executable checksum: cb09303cfa46f5ecbf59d9467eac8678
COLLECT_GCC_OPTIONS='-v' '-Oz' '-o' 'test.exe' '-nostartfiles' '-mcpu=arm7tdmi' '-mfloat-abi=soft' '-marm' '-mlibarch=armv4t' '-march=armv4t'
 C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/bin/as.exe -v -march=armv4t -mfloat-abi=soft -meabi=5 -o C:\Users\TOMMYM~1\AppData\Local\Temp\ccw1K8z4.o C:\Users\TOMMYM~1\AppData\Local\Temp\ccAqNSAw.s
GNU assembler version 2.41.0 (arm-none-eabi) using BFD version (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 2.41.0.20231009
COMPILER_PATH=C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../libexec/gcc/arm-none-eabi/13.2.1/;C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../libexec/gcc/;C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/bin/
LIBRARY_PATH=C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/;C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/;C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/lib/;C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../arm-none-eabi/lib/
COLLECT_GCC_OPTIONS='-v' '-Oz' '-o' 'test.exe' '-nostartfiles' '-mcpu=arm7tdmi' '-mfloat-abi=soft' '-marm' '-mlibarch=armv4t' '-march=armv4t' '-dumpdir' 'test.'
 C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../libexec/gcc/arm-none-eabi/13.2.1/collect2.exe -plugin C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../libexec/gcc/arm-none-eabi/13.2.1/liblto_plugin.dll -plugin-opt=C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../libexec/gcc/arm-none-eabi/13.2.1/lto-wrapper.exe -plugin-opt=-fresolution=C:\Users\TOMMYM~1\AppData\Local\Temp\ccWRMCxM.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc --sysroot=C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../arm-none-eabi -X -o test.exe -LC:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1 -LC:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc -LC:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/lib -LC:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../arm-none-eabi/lib C:\Users\TOMMYM~1\AppData\Local\Temp\ccw1K8z4.o --start-group -lgcc -lc --end-group
C:/Users/Tommy Murphy/Downloads/arm-gnu-toolchain-13.2.Rel1-mingw-w64-i686-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/bin/ld.exe: warning: cannot find entry symbol _start; defaulting to 00008000
COLLECT_GCC_OPTIONS='-v' '-Oz' '-o' 'test.exe' '-nostartfiles' '-mcpu=arm7tdmi' '-mfloat-abi=soft' '-marm' '-mlibarch=armv4t' '-march=armv4t' '-dumpdir' 'test.'

```

**Comment by ilg-ul** [comment]
Right, I double checked and it works for me too; previously I used 12.x, which does not support it.

The new 6.5.0 release is out.

**Pull request merged**
