### PR TITLE
#440 Split Java code between core & UI for Embedded CDT Packs

### PR DESCRIPTION
**Pull request by ruspl-afed**
Add PacksConsoleStream stream to be substituted by Eclipse UI Console if
available with OSGi component. Use simple System.out-based
implementation if UI Console is not available for some reason.
Avoid using JFace if not necessary.
Access packs.core preferences headless way where appropriate.

Signed-off-by: Alexander Fedorov <alexander.fedorov@arsysop.ru>

### CODE REVIEW

**Comment by ilg-ul** [comment]
The console improvement seems fine. Why don't we define the new classes at the top, in `org.eclipse.embedcdt.core`, to use them everywhere?

**Comment by ruspl-afed** [comment]
I tried to follow the "packs" scope. But yes, it can be moved upstream for better reuse. Should I do it in the scope of this PR?

**Comment by ilg-ul** [comment]
As you wish, we finally have to update all plug-ins, so it does not really matter how we split the changes.

**Comment by ruspl-afed** [comment]
ok, than I will use this PR to collect all the changes if you prefer to see this work as a single update.

**Comment by ilg-ul** [comment]
As you think more convenient, you're on a branch and it doesn't really matter, we'll merge it only when ready.

Be sure you merge the new master to your branch, to avoid more work after renaming folders.

**Comment by ruspl-afed** [comment]
> Be sure you merge the new master to your branch

I'm not sure how to do that in the right way. I'm working in the fork, as I'm not a committer. My fork is a kind of `from` the branch `eclipse-embed-cdt:develop-split` that I suppose was done from `develop` at some moment. Where is the `master` branch in this story?

**Comment by ruspl-afed** [comment]
@ilg-ul if you can update `eclipse-embed-cdt:develop-split` branch to be in the right state that may be an easiest solution for us.

**Comment by ilg-ul** [comment]
Sure, but to avoid messing things, can you confirm that this means merging both PRs? In what order?

So you prefer to 'Squash and merge' or 'Create a merge commit'?

**Comment by ruspl-afed** [comment]
I think I will close #439 and will include all the changes to this one.

**Comment by ilg-ul** [comment]
How do you plan to cope with the commits that happened on master after the develop-split was created?

For me it is easier to merge them now, but I guess you have to update you PRs.

**Comment by ruspl-afed** [comment]
Since I'm in the fork I would prefer to work with dedicated branch of original repo. Currently it is `develop-split`. Adding something from another branch via the fork looks more complicated for me.

So, please update the `develop-split` on your side to the state that you think will be the proper one. And then I will need to conform with it from this PR anyway.

**Comment by ilg-ul** [comment]
> please update the develop-split

Done, all branches are now up-to-date, the jenkins build passed, I tested the result and everything seems fine.

Unless major bugs are detected, I suggest we freeze the code until you complete your changes.

**Comment by ruspl-afed** [comment]
Conflicts resolved, I hope this PR now is up-to-date.

The remaining work:
* org.eclipse.embedcdt.debug.gdbjtag
* org.eclipse.embedcdt.debug.gdbjtag.jlink
* org.eclipse.embedcdt.debug.gdbjtag.jumper
* org.eclipse.embedcdt.debug.gdbjtag.openocd
* org.eclipse.embedcdt.debug.gdbjtag.pyocd
* org.eclipse.embedcdt.debug.gdbjtag.qemu
* org.eclipse.embedcdt.debug.gdbjtag.restart
* org.eclipse.embedcdt.managedbuild.cross
* org.eclipse.embedcdt.managedbuild.cross.arm

**Comment by ilg-ul** [comment]
Great! When you are ready and want to merge, please let me know exactly how to do it (order, type).

**Comment by ruspl-afed** [comment]
The remaining work:

* org.eclipse.embedcdt.debug.gdbjtag.jlink
* org.eclipse.embedcdt.debug.gdbjtag.jumper
* org.eclipse.embedcdt.debug.gdbjtag.openocd
* org.eclipse.embedcdt.debug.gdbjtag.pyocd
* org.eclipse.embedcdt.debug.gdbjtag.qemu
* org.eclipse.embedcdt.debug.gdbjtag.restart

**Comment by ilg-ul** [comment]
Great work!

**Comment by ruspl-afed** [comment]
@ilg-ul I'm done with split. This is the only PR that contains everything, another one was closed.

**Comment by ilg-ul** [comment]
Great!

I wonder if is still functional ;-)

Did you test anything? Any functional details to check?

**Comment by ilg-ul** [comment]
BTW, the minimum test to pass is the [blinky tutorial](https://eclipse-embed-cdt.github.io/tutorials/blinky-arm/), if you can create the blinky project, build it and run a qemu debug session, it is a good start.

**Comment by ruspl-afed** [comment]
I can see the toolchain and debug contributions.  And can create launch configurations as well as projects by RISC-V and ARM templates. Fixed double contribution for openocd in the last commit.

**Comment by ilg-ul** [comment]
When you're done with your tests, let me know, to merge the PR.

'Squash and merge' is ok?

**Comment by ruspl-afed** [comment]
> 'Squash and merge' is ok?

It is completely up to you. Usually I prefer to have small PRs, but for refactoring of that scale we can have an exclusion.

After installing all required things with xPack I can see the blinking board!

```

xPack 64-bit QEMU v2.8.0-10 (qemu-system-gnuarmeclipse.exe).
Board: 'STM32F4-Discovery' (ST Discovery kit for STM32F407/417 lines).
Device: 'STM32F407VG' (Cortex-M4 r0p0, MPU, ITM, 4 NVIC prio bits, 82 IRQs), Flash: 1024 kB, RAM: 128 kB.
Command line: 'blinky' (6 bytes).
Cortex-M4 r0p0 core initialised.
GDB Server listening on: 'tcp::1234'...
Cortex-M4 r0p0 core reset.

Other event 0x302
Other event 0x302
... connection accepted from ipv6 host.

Execute 'mon system_reset'.
Cortex-M4 r0p0 core reset.

PRIGROUP unimplemented
Other event 0x302
Other event 0x302
main(argc=1, argv=["blinky"]);
Hello Arm World!
Standard output message.
Standard error message.
System clock: 168000000 Hz
[led:green on]
[led:orange on]
[led:red on]
[led:blue on]
[led:green off]
[led:orange off]
[led:red off]
[led:blue off]
Second 1
[led:green on]
[led:green off]
Second 2
[led:orange on]
[led:orange off]
Second 3
[led:red on]
[led:red off]
Second 4
[led:blue on]
[led:blue off]
Second 5
[led:green on]
Second 6
[led:green off]
[led:orange on]
Second 7
[led:green on]
Second 8
[led:green off]
[led:orange off]
[led:red on]
Second 9
[led:green on]
Second 10
[led:green off]
[led:orange on]
Second 11
[led:green on]
Second 12
[led:green off]
[led:orange off]
[led:red off]
[led:blue on]
Second 13
[led:green on]
Second 14
[led:green off]
[led:orange on]
Second 15
[led:green on]
Second 16
[led:green off]
[led:orange off]
[led:red on]
Second 17
[led:green on]
Second 18
[led:green off]
[led:orange on]
Second 19
[led:green on]
Second 20
[led:green off]
[led:orange off]
[led:red off]
[led:blue off]
Second 21
[led:green on]
[led:orange on]
[led:red on]
[led:blue on]

QEMU semihosting exit(0)
```

**Comment by ruspl-afed** [comment]
@ilg-ul I think I'm done with this PR. Anyway I need to switch to other things for a while. Please let me know if something lese needs to be done here.

**Comment by ilg-ul** [comment]
> I can see the blinking board!

Super! Great work!

I'll proceed with some tests on my side.

**Comment by ilg-ul** [comment]
I saw you added gdbjtag-feature with the core plug-ins. What is the use case for this new feature?

**Comment by ruspl-afed** [comment]
It is internal feature to be reused by  other gdbjtag* features. Just to reduce the duplication (and potential errors) in the feature manifests. It can be "inlined" back if needed.

**Comment by ilg-ul** [comment]
If it is _internal_, then I don't have to add it to EPP & SimRel, right?

**Comment by ruspl-afed** [comment]
Yes, all should continue working without adding every internal feature. 
So, I suppose you can keep your SimRel contribution "as is" from the features perspective.

**Comment by ilg-ul** [comment]
Alexander @ruspl-afed , I'm thinking to somehow reduce clutter, now there are a lot more plug-ins.

How about suffixing the branding plug-ins with `-branding` and moving them to the `features` folder? 

To me they seem more related to the features and less to the plug-ins and I guess they rarely need any changes.

What do you think?

**Comment by ilg-ul** [comment]
I suffixed those plug-ins as `-branding` and moved them to a separate folder.

**Comment by ilg-ul** [comment]
Alexander @ruspl-afed, I noticed that in `org.eclipse.embedcdt.ui` you moved the preferences & properties pages to the internal packages. Can you help me understand the reason? Since there are such pages in other plug-ins too, and perhaps we should move all of them.

Jonah @jonahgraham, any suggestions?

**Comment by jonahgraham** [comment]
@ilg-ul In the past (eg in a lot of CDT) way too much stuff is public API. I personally would limit what is official API as much as possible (yet still export all packages with x-internal or x-friends). So if @ruspl-afed reduced how much stuff is exported as API I am 100% in favour of that.

**Comment by ruspl-afed** [comment]
Liviu @ilg-ul this was to highlight that they are not supposed to be API. If you do not agree with that please move them back.
Generally I recommend to shorter the amount of API packages to reduce the support effort. It can be done with declaring package as x-internal (or with x-friends if needed) in MANIFEST.MF without moving to 'internal' package.

**Comment by ruspl-afed** [comment]
> To me they seem more related to the features and less to the plug-ins and I guess they rarely need any changes.
> What do you think?

Sorry, missed your message @ilg-ul 
I'm ok to extract branding bundles to a separate folder. In big source bases I use ".branding" postfix and "branding" folder sibling to "features".
However it does not help a lot with amount of bundes. Workink Sets does. https://dzone.com/articles/eclipse-working-sets-explained

**Comment by ilg-ul** [comment]
Yes, the principle to have less public API is great, but I don't know the criteria to tell which classes should be internal. 

What makes the preferences/properties internal? And what other classes should be internal too? Perspectives? Views? 

If I understand the reasoning, I can apply it to the entire project, but for now I have no idea.

**Comment by ilg-ul** [comment]
> Working sets

Yes, I know about working sets, I used them before.

I also renamed the description of the plug-ins to explicitly mention 'Branding'. Now it is clear which is which when reading the full list of plug-ins, just that there are quite a lot.

**Comment by ruspl-afed** [comment]
> Yes, the principle to have less public API is great, but I don't know the criteria to tell which classes should be internal.
> 
> What makes the preferences/properties internal? And what other classes should be internal too? Perspectives? Views?

The general rule is: do you intend the downstream bundle to instantiate and call your class in their code?

Typically NO: for preference pages, views, perspectives
Typically YES: for identifiers of preferences, views, perspectives.

Typically, because personally I do not support exposing identifiers to API. Embedded CDT is the perfect example why. Because it is insufficient to know preference id, one should call the dedicated code that knows _how_ to load preference properly.

**Comment by ilg-ul** [comment]
Alexander @ruspl-afed, I noticed that in the files you edited, the lines are terminated by CR LF, not LF only, as it is recommended for a better portability. I think that you should configure your Git to commit the files without CR.

Now I have to find a way to clean the files...

**Comment by ruspl-afed** [comment]
> Alexander @ruspl-afed, I noticed that in the files you edited, the lines are terminated by CR LF, not LF only, as it is recommended for a better portability. I think that you should configure your Git to commit the files without CR.
> 
> Now I have to find a way to clean the files...

Sorry, this was unintentional. Do you think `.gitattributes` with `* text=auto eol=lf` can prevent the sources from being converted in the future?

**Comment by ilg-ul** [comment]
> The general rule is: do you intend the downstream bundle to instantiate and call your class in their code?

Well, in this case I think that after I push the changes I worked on these days, we should do a second iteration and decide what should go to the internal classes, since I'm not able to decide alone.

**Comment by ruspl-afed** [comment]
> Now I have to find a way to clean the files...

Eclipse can do this via File -> Convert Line Delimeters To

**Comment by jonahgraham** [comment]
run dos2unix on all files: https://formulae.brew.sh/formula/dos2unix

The CDT build has a check that all files have the correct line endings (And a .gitattributes to try to make sure they don't get wrong in the first place)

**Comment by ilg-ul** [comment]
It seems that 'File -> Convert Line Delimiters To' on the entire project fixed the issue.

**Comment by ilg-ul** [comment]
> a .gitattributes 

Which attribute? I tried to make some sense from the git documentation, but I'm not smart enough. :-(

**Comment by ilg-ul** [comment]
I pushed my commits to move the branding plug-ins and to fix various other issues.

The result seems generally ok, the only victim I noticed is the Outline view in the Packs perspective, which was somehow affected by the first set of changes during the split. I'll try to diagnose it tomorrow.

**Comment by ilg-ul** [comment]
> the Outline view in the Packs perspective

Alexander @ruspl-afed, the Outline view is empty because the code in ParsePdscRunnable.jave to parse the outline is no longer executed (a breakpoint placed in `ParsePdscRunnable.run()` is not reached).

The change that I identified in your patch is in OutlineView.java, around line 490:

```
// progressService.busyCursorWhile(new ParsePdscRunnable("Parse Outline", (PackNode) versionNode));
progressService.busyCursorWhile(m-> new ParsePdscRunnable("Parse Outline", (PackNode) versionNode));
```

It looks like now a runnable is slightly different from what I used in my old implementation.

I'll continue to chase it down, but any help will be appreciated.

**Comment by ruspl-afed** [comment]
I cannot hit this code and Outline shows content for me, but the code should be 
```java
			progressService.busyCursorWhile(m-> new ParsePdscRunnable("Parse Outline", (PackNode) versionNode).run(m));
```

**Comment by ilg-ul** [comment]
Thank you, but In the mean time I moved the runner to the .ui plug-in and reverted to the old code, which I knew to be functional.

**Comment by ruspl-afed** [comment]
Thank you for fixing this.

**Comment by ilg-ul** [comment]
No problem, your solution is obviously better, I moved the class back to .core, now it works.

**Pull request merged**
