### PR TITLE
Cross toolchain support for CDT object file build artifact

### PR DESCRIPTION
**Pull request by baoruiqi**
Hi, all

This pull request is an addition to the new object file build artifact issue in CDT where motivations and practices are mentioned in eclipse-cdt/cdt#394

### CODE REVIEW

**Comment by ilg-ul** [comment]
Please address your patch to the Eclipse CDT project.

**Comment by baoruiqi** [comment]
Here,
eclipse-cdt/cdt/pull/418

**Comment by baoruiqi** [comment]
@ilg-ul 

This pull request has been closed without any comment, could you give me some more information? I wonder if my patch has no value or there is any other reason?

Thank you!

**Comment by jonahgraham** [comment]
I think what happened here is  @ilg-ul asked if you could submit to CDT in https://github.com/eclipse-embed-cdt/eclipse-plugins/pull/573#issuecomment-1590475309 and when you acknowledged that in https://github.com/eclipse-embed-cdt/eclipse-plugins/pull/573#issuecomment-1590520931 @ilg-ul considered the issued resolved in this repo.

With the PR in CDT, is there anything additional needed in embed-cdt?

**Comment by ilg-ul** [comment]
Right, sorry for not providing any feedback, I thought it was self explanatory. Since the PR is not specific to Embed CDT, if it is accepted by CDT it'll automatically be used by the next release of Embed CDT.

**Pull request closed without merging**
