### PR TITLE
Add Gigadevice MCU Templates

### PR DESCRIPTION
**Pull request by gd32swteam**
Add new folders under the "bundles" and "features", named as "ilg.gnumcueclipse.templates.gd" and "ilg.gnumcueclipse.templates.gd.feature", include code that implement GD32E23x and GD32VF103 templates functionality.

### CODE REVIEW

**Comment by ilg-ul** [comment]
Hi Xiaoxue,

I'm right in the middle of installing my new computer, and I can't check your code, it'll probably take me a few more days to get to it.

In the mean time I'd prefer you to fix all issues and first publish your plug-ins on a separate update site. Once everything is functional we'll add them to GME.

**Comment by gd32swteam** [comment]
Okey ,thank you.

**Comment by ilg-ul** [comment]
Hi @gd32swteam,

As you might have noticed, the project was greatly changed and is not part of the Eclipse Foundation.

After all these changes, this pull request is no longer possible, but I reopened it since in a future release I plan to update all project templates, and also include a GigaDevice template.

**Comment by ilg-ul** [comment]
@gd32swteam, FYI, I just received a GD32VF103C-START board from TME Poland, requested by a colleague, Kristof Mulier, from Belgium. He also mentioned that he wrote to his contacts at GigaDevice in China, asking to send me more boards and generally for more support in pushing this through.

If you are interested in this, please contact me on my private email address <ilg@livius.net> to discuss the details.

**Comment by jonahgraham** [comment]
> is not part of the Eclipse Foundation.

[...] is *now* part [...]

**Pull request closed without merging**
