### PR TITLE
#391 Releng: clean up the respository manifests

### PR DESCRIPTION
**Pull request by ruspl-afed**
Remove duplicated group and version for artifact in pom.xml
Remove unused url and version attributes for feature in category.xml

Signed-off-by: Alexander Fedorov <alexander.fedorov@arsysop.ru>

### CODE REVIEW

**Comment by ruspl-afed** [comment]
@ilg-ul the travis was not triggered for the PR, is it intentional?

**Comment by ruspl-afed** [comment]
Ah, in fact it was, but this is not a part of "checks". I would consider to employ GiHub Actions as they are more powerful and better integrated. @ilg-ul WDYT?

**Comment by ilg-ul** [comment]
> the travis was not triggered for the PR

No, unfortunately this is just another joy of migrating the project to the foundation organisation, permanent friction with the admins :-(

I asked for rights to enable Travis a few days ago, but so far received no reply.

**Comment by ilg-ul** [comment]
> GiHub Actions

Yes, I play a bit with it, but every such small change require time to implement and test, and I I don't know what to do first...

For now I would stick with what is functional, and address changes one my one, time permitting.

**Comment by ilg-ul** [comment]
You based your changes on `develop`, which is a bit behind `master`. Would it be ok to merge it?

**Comment by ruspl-afed** [comment]
> You based your changes on develop, which is a bit behind master

 **submit the pull request to the develop branch**

this is what I can read in https://github.com/eclipse-embed-cdt/eclipse-plugins/blob/develop/CONTRIBUTING.md

**Comment by ilg-ul** [comment]
> this is what I can read in

:-(

Yes, just that I started work on the new release, which is built from master, and I forgot to update develop.

How can we fix this? If I merge this, should I next merge master into develop?

**Comment by ruspl-afed** [comment]
I changed base to `master` , but probably you can publish/update the policy? Currently the `develop` is default branch and it is not clear that `master` should be preferred.

**Comment by ilg-ul** [comment]
`develop` is preferred, just that now I was a bit sloppy in maintaining the repo consistent with the policy.

**Pull request merged**
