### PR TITLE
Numerous pyocd updates

### LINKED ISSUE #349: GDB PyOCD Debugging debug configuration opens very slowly on Windows
### Description

When you open PyOCD debug configuration Eclipse hangs for approximately 15 seconds, only after that time debug configuration is available. Opening PyOCD debug configurations is extremely painful when you need to make some fixes few times in a row.

Key notes:
- reproducible on Windows only
- not reproducible if PyOCD path points to wrong location
- there are a lot of TCP/IP traffic when you open PyOCD debug configuration - for some reason plugin communicates with pyocd gdb
- this is not machine-specific, I have heard from lots of people about this problem

### Steps to Reproduce
1. Create new fresh workspace
2. Create new Project
 - go to **File** -> **New** -> **C/C++ Project**
 - select **C Managed Build** and press **Next**
 - fill in **Project name**
 - select **Project type** = **Empty Project**
 - select **Toolchains** = **Cross GCC**
 - Press **Next**, **Next**, then **Finish**
3. Create new debug configuration
 - go to **Run** -> **Debug Configurations**
 - right click the **GDB PyOCD Debugging** and choose **New Configuration**. Creation takes up to 15 seconds (for OpenOCD time is < 1 second)
4. close **Debug Configurations** window
5. go to **Run** -> **Debug Configurations** and select PyOCD debug configurations. Observe it hangs for ~ 15 seconds

Screen capture: https://drive.google.com/open?id=19quDPapnm-weUgKgK6Nfpx4AqBjn_6nH

**Expected behaviour:**
PyOCD debug configurations opens faster (like OpenOCD does, it takes up to 1 second)
**Actual behaviour:**
PyOCD debug configurations opens ~ 15 seconds

### Versions

* pyocd 0.21.0
* GNU MCU Eclipse 4.5.1.201901011632
* Eclipse IDE for C/C++ Developers. Version: 2018-09 (4.9.0). Build id: 20180917-1800
* Eclipse CDT Version: 9.5.5.201811180605
* Java 8 Update 211
* Windows 10 Pro x64
* Cross GCC, but that actually does not matter

---

### PR DESCRIPTION
**Pull request by flit**
This pull request combines updates, bug fixes, and general improvements for the pyOCD launch config plugin.

Major changes:
- Support for modern `pyocd` combined tool (instead of deprecated `pyocd-gdbserver` tool).
- The majority of the changes are related to the fix for #349. All calls out to pyocd are performed asynchronously on a DSF executor thread and the results returned via a `DataRequestMonitor<?>`. While waiting for a call to pyocd to finish, a message is shown in the launch config window.
- When a launch config doesn't have a probe saved in it (e.g. a new config) the probes popup menu has a "\<Please select a debug probe>" item that is selected.
- Similarly, when the launch config has a probe saved in it that isn't currently available, it includes a menu item in the probes popup for the unconnected probe.
- Passing the ELF file to pyocd via its `--elf` argument.
- Various fixes for NPE and other issues.
- Lots of code cleanup.

(There is still a lot of room for improvement after this PR, mostly in supporting all the features pyocd has gained in the last 4-5 years since the plugin was first written.)

Fixes #349

### CODE REVIEW

**Comment by ilg-ul** [comment]
Hi Chris, 

Thank you for the PR, I guess it is ok.

However, I see that the CI check complains about an outdated ECA. 

Jonah @jonahgraham, what should we do in order to merge this PR?

**Comment by flit** [comment]
Whoops, just tell me what I need to do.

**Comment by jonahgraham** [comment]
Thanks @flit for the improvements. The project is  part of the Eclipse Foundation and we need you to sign the ECA and sign off your git commits. 

To sign ECA visit  https://accounts.eclipse.org/user/eca and complete the online form. 

Thanks, and please let me know if you have any further questions.

**Comment by flit** [comment]
Done!

**Comment by ilg-ul** [comment]
I could not find any way to rerun the CI job. 

Unless Jonah knows a trick, you'll probably have to push something to trigger a new check.

**Comment by jonahgraham** [comment]
I don't know why, but neither of the email addresses (flit@me or chris..@nxp) in these commits are passing the ECA check. Also, I note on your profile a third address (chris...@arm).

Which one did you sign the ECA with? The commits need to be authored by that email address. I recommend all the commits be by the same author email address - I don't know how/if to handle multiple email addresses from the same user.

Also, the commits need to be signed off. Run git commit --amend --sign-off. 

See https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Eclipse_Contributor_Agreement and https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Signing_off_on_a_commit for more info.

Thanks.
Jonah

**Comment by flit** [comment]
Normally I use only flit@me for personal contributions and (try to) use chris@arm for work contributions. But since some of these changes are originally from quite a while ago, there's the commit with chris@nxp from before I moved to Arm.  I'll have to recreate that commit since I obviously can't create an account to sign the ECA. Anyway, I've signed the ECA with all the email addresses that might be used; sadly there's no way to associate multiple email addresses with an Eclipse account so it's kind of a pain to manage.

Thanks for the tip about signing off the commits.

**Comment by ilg-ul** [comment]
It seems ok now. If Jonah also agrees, we can merge these commits.

**Comment by jonahgraham** [comment]
Thanks @flit for jumping through the hoops. Next time it will be easier. The ECA checker had approved this pr, so @ilg-ul it is good to go!

**Comment by flit** [comment]
No worries! I appreciate your guidance here. 😄

**Comment by ilg-ul** [comment]
Done.

Thank you, Chris.

**Comment by flit** [comment]
Thank you!

**Comment by ilg-ul** [comment]
The new release candidate, which includes the new pyocd plug-ins, is available for testing from:

- https://download.eclipse.org/embed-cdt/updates/v6-test/

**Pull request merged**
