### PR TITLE
WIP: Employ GitHub Actions to run on push and pull_request

### PR DESCRIPTION
**Pull request by ruspl-afed**
Let's try how the pipeline would look with GitHub Actions

Signed-off-by: Alexander Fedorov <alexander.fedorov@arsysop.ru>

### CODE REVIEW

**Comment by ruspl-afed** [comment]
Hmm, not included to the pipeline also. 
Dear @eclipsewebmaster , what is included in the pipeline by default and how @ilg-ul can engage you to apply the right settings to this repository?

**Comment by ilg-ul** [comment]
As I said, I'd prefer continuing using Travis for a while, and change to Actions at a later moment.

**Comment by ruspl-afed** [comment]
ok, do we have a bugzilla ticket for @eclipsewebmaster to add Travis to the pipeline?

**Comment by ilg-ul** [comment]
I did a push and the action triggered, so I guess it is ok.

Thank you!

**Pull request merged**
