### PR TITLE
Fix Eclipse CI build status badge

### PR DESCRIPTION
**Pull request by ruspl-afed**
Update fork

### CODE REVIEW

**Comment by ilg-ul** [comment]
CI is ok, isn't it?

**Comment by ruspl-afed** [comment]
Yes, it works now. May be we can retire Travis.

**Comment by ilg-ul** [comment]
You mean to remove the .yml file?

**Comment by ruspl-afed** [comment]
Yes. I would say "and change repository settings" but I suppose there is nothing to change there as it was never working.

**Comment by ruspl-afed** [comment]
@ilg-ul  please have a look on README in my fork - build status works good https://github.com/ruspl-afed/eclipse-plugins/

**Comment by ilg-ul** [comment]
The Jenkins job is not CI, I trigger it only when I want the result published in the builds folder, so I guess the badge should not point to it, but to the GitHub Actions.

**Comment by ilg-ul** [comment]
> I would say "and change repository settings" but I suppose there is nothing to change there as it was never working.

It worked before the migration.

There is still a web hook pointing to Travis, should I remove it?

**Comment by ruspl-afed** [comment]
> The Jenkins job is not CI, I trigger it only when I want the result published in the builds folder, so I guess the badge should not point to it, but to the GitHub Actions.

Done

**Comment by ruspl-afed** [comment]
> > I would say "and change repository settings" but I suppose there is nothing to change there as it was never working.
> 
> It worked before the migration.
> 
> There is still a web hook pointing to Travis, should I remove it?

Yes, I would stick to GitHub actions - at the moment it is the best choice for GitHub

**Comment by ilg-ul** [comment]
Great, thank you!

If we find a solution to enable stats for the p2 repo, I think we can consider to release 5.1.2.

**Comment by ilg-ul** [comment]
.travis.yml removed, and the webhook deleted.

**Pull request merged**
